"""Performance analysis engine for the trading bot.

Breaks down historical performance across multiple dimensions -- setup type,
symbol, time of day, day of week, and confluence score -- to surface
statistically meaningful edges and weaknesses.

The analyzer produces both raw metrics and human-readable recommendations that
can be fed directly into the parameter optimizer or presented on the dashboard.

Key statistical measures:
    - **Sharpe ratio**: risk-adjusted return; penalises variance.
    - **Profit factor**: gross wins / gross losses; values > 1.5 are strong.
    - **Max drawdown**: largest peak-to-trough decline in equity.
"""

import math
from collections import defaultdict
from datetime import datetime
from typing import Any, Dict, List, Optional


class PerformanceAnalyzer:
    """Multi-dimensional performance analysis of historical trades.

    Works with a TradeJournal instance for data retrieval and produces
    structured analysis dicts plus actionable recommendation strings.
    """

    def __init__(self, database, journal) -> None:
        self.db = database
        self.journal = journal

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def analyze(self, bot_name: Optional[str] = None) -> dict:
        """Run comprehensive performance analysis.

        Args:
            bot_name: Optional filter; None analyses all bots.

        Returns:
            Dictionary with sections:
                overall   - aggregate metrics
                by_setup  - metrics keyed by setup_type
                by_symbol - metrics keyed by symbol
                by_time   - metrics keyed by hour_of_day and day_of_week
                by_confluence - metrics bucketed by confluence score ranges
        """
        trades = await self.journal.get_trades(bot_name=bot_name)

        if not trades:
            return {
                "overall": self._empty_overall(),
                "by_setup": {},
                "by_symbol": {},
                "by_time": {"by_hour": {}, "by_day": {}},
                "by_confluence": {},
            }

        overall = self._compute_overall(trades)
        by_setup = self._group_and_compute(trades, "setup_type")
        by_symbol = self._group_and_compute(trades, "symbol")
        by_time = self._compute_time_analysis(trades)
        by_confluence = self._compute_confluence_analysis(trades)

        return {
            "overall": overall,
            "by_setup": by_setup,
            "by_symbol": by_symbol,
            "by_time": by_time,
            "by_confluence": by_confluence,
        }

    async def generate_recommendations(self, analysis: dict) -> List[str]:
        """Produce actionable text recommendations from an analysis dict.

        Recommendations are generated by comparing sub-group performance
        against overall baselines and flagging meaningful deviations.

        Args:
            analysis: The dict returned by ``analyze()``.

        Returns:
            A list of human-readable recommendation strings.
        """
        recs: List[str] = []
        overall = analysis.get("overall", {})
        overall_wr = overall.get("win_rate", 0.0)

        # --- Setup-type recommendations ---
        for setup, metrics in analysis.get("by_setup", {}).items():
            count = metrics.get("total", 0)
            wr = metrics.get("win_rate", 0.0)
            if count >= 20 and wr < 0.35:
                recs.append(
                    f"Disable {setup} entries - "
                    f"{wr:.0%} win rate over {count} trades"
                )
            elif count >= 20 and wr > overall_wr + 0.10:
                recs.append(
                    f"Prioritise {setup} setups - "
                    f"{wr:.0%} win rate vs {overall_wr:.0%} overall "
                    f"({count} trades)"
                )

        # --- Symbol recommendations ---
        for symbol, metrics in analysis.get("by_symbol", {}).items():
            count = metrics.get("total", 0)
            wr = metrics.get("win_rate", 0.0)
            if count >= 15 and wr < 0.35:
                recs.append(
                    f"Consider removing {symbol} - "
                    f"{wr:.0%} win rate over {count} trades"
                )

        # --- Time-based recommendations ---
        by_hour = analysis.get("by_time", {}).get("by_hour", {})
        for hour, metrics in by_hour.items():
            count = metrics.get("total", 0)
            wr = metrics.get("win_rate", 0.0)
            if count >= 10 and wr < 0.30:
                recs.append(
                    f"Avoid trading at hour {hour} UTC - "
                    f"{wr:.0%} win rate over {count} trades"
                )

        by_day = analysis.get("by_time", {}).get("by_day", {})
        day_names = {
            0: "Monday", 1: "Tuesday", 2: "Wednesday",
            3: "Thursday", 4: "Friday", 5: "Saturday", 6: "Sunday",
        }
        for day, metrics in by_day.items():
            count = metrics.get("total", 0)
            wr = metrics.get("win_rate", 0.0)
            if count >= 10 and wr < 0.30:
                name = day_names.get(int(day), str(day))
                recs.append(
                    f"Avoid trading on {name} - "
                    f"{wr:.0%} win rate over {count} trades"
                )

        # --- Confluence score recommendations ---
        confl = analysis.get("by_confluence", {})
        high_bucket = confl.get("70-100", {})
        low_bucket = confl.get("0-50", {})
        if (
            high_bucket.get("total", 0) >= 20
            and low_bucket.get("total", 0) >= 20
        ):
            high_wr = high_bucket.get("win_rate", 0.0)
            low_wr = low_bucket.get("win_rate", 0.0)
            if high_wr - low_wr > 0.10:
                recs.append(
                    f"Increase min confluence to 70 - "
                    f"trades with score 70+ have {high_wr:.0%} win rate "
                    f"vs {low_wr:.0%} for score < 50"
                )

        if not recs:
            recs.append("No strong recommendations yet - more data needed")

        return recs

    # ------------------------------------------------------------------
    # Statistical helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _calculate_sharpe(returns: List[float], risk_free_rate: float = 0.0) -> float:
        """Compute annualised Sharpe ratio from a series of trade returns.

        Sharpe = (mean_return - risk_free) / std_dev * sqrt(N)
        where N is the number of observations (trades).  Because trade
        frequency is irregular, we report the *per-trade* Sharpe multiplied
        by sqrt(252) as a rough annual proxy.

        Args:
            returns: Per-trade percentage returns.
            risk_free_rate: Per-trade risk-free return (default 0).

        Returns:
            Annualised Sharpe ratio. Returns 0.0 when there are fewer than
            2 observations or zero variance.
        """
        if len(returns) < 2:
            return 0.0
        mean_r = sum(returns) / len(returns) - risk_free_rate
        variance = sum((r - mean_r - risk_free_rate) ** 2 for r in returns) / (len(returns) - 1)
        std = math.sqrt(variance) if variance > 0 else 0.0
        if std == 0.0:
            return 0.0
        # Annualise assuming ~252 trading days
        return (mean_r / std) * math.sqrt(252)

    @staticmethod
    def _calculate_max_drawdown(equity_curve: List[float]) -> float:
        """Compute maximum drawdown from an equity curve.

        The equity curve is a running cumulative sum; max drawdown is the
        largest percentage decline from a peak to any subsequent trough.

        Args:
            equity_curve: Cumulative equity values (e.g. [100, 105, 98, ...]).

        Returns:
            Max drawdown as a positive fraction (e.g. 0.15 for 15%).
            Returns 0.0 for empty or monotonically increasing curves.
        """
        if len(equity_curve) < 2:
            return 0.0
        peak = equity_curve[0]
        max_dd = 0.0
        for value in equity_curve:
            if value > peak:
                peak = value
            if peak > 0:
                dd = (peak - value) / peak
                max_dd = max(max_dd, dd)
        return max_dd

    @staticmethod
    def _calculate_profit_factor(wins: List[float], losses: List[float]) -> float:
        """Profit factor = gross profit / gross loss.

        Args:
            wins: Positive PnL values.
            losses: Negative PnL values (will be abs'd).

        Returns:
            Profit factor. Returns inf when there are no losses.
        """
        gross_profit = sum(wins)
        gross_loss = sum(abs(l) for l in losses)
        if gross_loss == 0:
            return float("inf") if gross_profit > 0 else 0.0
        return gross_profit / gross_loss

    # ------------------------------------------------------------------
    # Internal analysis helpers
    # ------------------------------------------------------------------

    def _compute_overall(self, trades: List[dict]) -> dict:
        """Compute aggregate metrics across all supplied trades."""
        pnls = [t.get("pnl", 0.0) for t in trades]
        wins = [p for p in pnls if p > 0]
        losses = [p for p in pnls if p <= 0]
        r_vals = [t.get("r_multiple", 0.0) for t in trades if t.get("r_multiple") is not None]

        # Build equity curve starting at a notional 10 000
        equity = [10000.0]
        for p in pnls:
            equity.append(equity[-1] + p)

        # Per-trade percentage returns for Sharpe
        returns = []
        for i, p in enumerate(pnls):
            base = equity[i] if equity[i] != 0 else 1.0
            returns.append(p / base)

        return {
            "total_trades": len(trades),
            "win_rate": len(wins) / len(trades) if trades else 0.0,
            "profit_factor": self._calculate_profit_factor(wins, losses),
            "avg_r": sum(r_vals) / len(r_vals) if r_vals else 0.0,
            "sharpe_ratio": self._calculate_sharpe(returns),
            "max_drawdown": self._calculate_max_drawdown(equity),
            "total_pnl": sum(pnls),
        }

    def _empty_overall(self) -> dict:
        return {
            "total_trades": 0,
            "win_rate": 0.0,
            "profit_factor": 0.0,
            "avg_r": 0.0,
            "sharpe_ratio": 0.0,
            "max_drawdown": 0.0,
            "total_pnl": 0.0,
        }

    def _group_and_compute(self, trades: List[dict], key: str) -> Dict[str, dict]:
        """Group trades by *key* and compute win_rate + avg_r per group."""
        groups: Dict[str, List[dict]] = defaultdict(list)
        for t in trades:
            groups[t.get(key, "unknown")].append(t)

        result: Dict[str, dict] = {}
        for group_key, group_trades in groups.items():
            wins = [t for t in group_trades if t.get("pnl", 0) > 0]
            r_vals = [
                t.get("r_multiple", 0.0)
                for t in group_trades
                if t.get("r_multiple") is not None
            ]
            result[group_key] = {
                "total": len(group_trades),
                "win_rate": len(wins) / len(group_trades) if group_trades else 0.0,
                "avg_r": sum(r_vals) / len(r_vals) if r_vals else 0.0,
            }
        return result

    def _compute_time_analysis(self, trades: List[dict]) -> dict:
        """Break down performance by hour of day and day of week."""
        by_hour: Dict[int, List[dict]] = defaultdict(list)
        by_day: Dict[int, List[dict]] = defaultdict(list)

        for t in trades:
            raw_time = t.get("entry_time")
            if raw_time is None:
                continue
            if isinstance(raw_time, str):
                try:
                    dt = datetime.fromisoformat(raw_time)
                except ValueError:
                    continue
            elif isinstance(raw_time, datetime):
                dt = raw_time
            else:
                continue
            by_hour[dt.hour].append(t)
            by_day[dt.weekday()].append(t)

        def _summarise(group: List[dict]) -> dict:
            wins = [t for t in group if t.get("pnl", 0) > 0]
            r_vals = [t.get("r_multiple", 0.0) for t in group if t.get("r_multiple") is not None]
            return {
                "total": len(group),
                "win_rate": len(wins) / len(group) if group else 0.0,
                "avg_r": sum(r_vals) / len(r_vals) if r_vals else 0.0,
            }

        return {
            "by_hour": {h: _summarise(g) for h, g in sorted(by_hour.items())},
            "by_day": {d: _summarise(g) for d, g in sorted(by_day.items())},
        }

    def _compute_confluence_analysis(self, trades: List[dict]) -> dict:
        """Bucket trades by confluence score ranges and compute metrics."""
        buckets: Dict[str, List[dict]] = {
            "0-50": [],
            "50-60": [],
            "60-70": [],
            "70-100": [],
        }

        for t in trades:
            score = t.get("confluence_score", 0.0)
            if score is None:
                continue
            if score < 50:
                buckets["0-50"].append(t)
            elif score < 60:
                buckets["50-60"].append(t)
            elif score < 70:
                buckets["60-70"].append(t)
            else:
                buckets["70-100"].append(t)

        result: Dict[str, dict] = {}
        for label, group in buckets.items():
            if not group:
                result[label] = {"total": 0, "win_rate": 0.0, "avg_r": 0.0}
                continue
            wins = [t for t in group if t.get("pnl", 0) > 0]
            r_vals = [t.get("r_multiple", 0.0) for t in group if t.get("r_multiple") is not None]
            result[label] = {
                "total": len(group),
                "win_rate": len(wins) / len(group),
                "avg_r": sum(r_vals) / len(r_vals) if r_vals else 0.0,
            }
        return result
